/// Actions the app can take in response to a key press.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Action {
    Quit,
    Back,
    MoveUp,
    MoveDown,
    PageUp,
    PageDown,
    JumpTop,
    JumpBottom,
    Select,
    OpenMessage,
    Compose,
    Reply,
    ReplyAll,
    Forward,
    Delete,
    ToggleFlag,
    ToggleRead,
    CycleTriageLane,
    RouteSender(crate::db::sender_routes::Route),
    OpenFollowup(crate::db::message_markers::Marker),
    ToggleMarker(crate::db::message_markers::Marker),
    ToggleMuteConversation,
    OpenResurface,
    ResurfaceInput(char),
    ResurfaceBackspace,
    ResurfaceSubmit,
    ResurfaceCancel,
    OpenPlacePrompt,
    RouteMessage(crate::db::sender_routes::Route),
    PlaceCancel,
    OpenNote,
    OpenSubjectAlias,
    AnnotationInput(char),
    AnnotationBackspace,
    AnnotationSubmit,
    AnnotationCancel,
    OpenAttachmentLibrary,
    AttachmentLibraryNext,
    AttachmentLibraryPrev,
    AttachmentLibraryOpen,
    AttachmentLibraryClose,
    OpenReadTogether,
    OpenBypassPrompt,
    BypassInput(char),
    BypassBackspace,
    BypassSubmit,
    BypassGenerate,
    BypassCancel,
    ToggleCoverReveal,
    SyncFolder,
    MarkFolderRead,
    DownloadAttachments,
    DownloadAttachmentsZip,
    ToggleThread,
    Search,
    SearchSubmit,
    SearchCancel,
    /// Toggle searching every folder from the search prompt.
    ToggleSearchScope,
    SearchInput(char),
    SearchBackspace,
    Refresh,
    SwitchAccount,
    ToggleHelp,
    ToggleHeaders,
    ToggleQuotes,
    ToggleHtmlSource,
    SaveMessage,
    FocusFolders,
    FocusEnvelopes,
    MoveMessage,
    CopyMessage,
    MoveInput(char),
    MoveBackspace,
    MoveNext,
    MovePrev,
    MoveSubmit,
    MoveCancel,
    UnlockPrompt,
    UnlockInput(char),
    UnlockBackspace,
    UnlockSubmit,
    UnlockCancel,
    /// Trust the S/MIME signer certificate of the current message.
    TrustSigner,
    AccountNew,
    AccountEdit,
    AccountEditFieldNext,
    AccountEditFieldPrev,
    AccountEditInput(char),
    AccountEditBackspace,
    AccountEditToggleDefault,
    AccountEditSave,
    AccountEditCancel,
    /// Auto-detect provider settings for the typed login.
    AccountEditDiscover,
    /// Cycle the contact tag filter.
    CycleContactTag,
    OpenFilePicker,
    FilePickerNext,
    FilePickerPrev,
    FilePickerEnter,
    FilePickerUp,
    FilePickerClose,
    OpenOutbox,
    OutboxNext,
    OutboxPrev,
    OutboxSend,
    OutboxDiscard,
    OutboxClose,
    // ── Settings ──────────────────────────────────────────────────────
    OpenSettings,
    SettingsToggleNotifications,
    SettingsNext,
    SettingsPrev,
    SettingsClose,
    // ── Scheduled send ────────────────────────────────────────────────
    OpenSchedule,
    ScheduleInput(char),
    ScheduleBackspace,
    ScheduleSubmit,
    ScheduleCancel,
    // ── Invitation replies ────────────────────────────────────────────
    /// Add a message's calendar invitation to Planner123.
    AddToPlanner,
    // ── Folder management ─────────────────────────────────────────────
    FolderNew,
    FolderRename,
    FolderDelete,
    FolderSubscribe,
    FolderPromptInput(char),
    FolderPromptBackspace,
    FolderPromptSubmit,
    FolderPromptCancel,
    // ── Multi-select ──────────────────────────────────────────────────
    ToggleSelect,
    /// Reverse the last destructive action.
    Undo,
    /// Jump to the next unread message.
    NextUnread,
    /// Jump to the previous unread message.
    PrevUnread,
    // ── Folder incremental search ─────────────────────────────────────
    FolderJumpInput(char),
    FolderJumpBackspace,
    FolderJumpClear,
    /// Cycle the message-list ordering.
    CycleSortOrder,
    /// Mark every message in the cursor's thread read.
    MarkThreadRead,
    /// Move the selection to the archive folder.
    Archive,
    /// Make the highlighted account the default.
    SetDefaultAccount,
    /// Delete the highlighted account.
    DeleteAccount,
    /// Hide the replies of the cursor's thread.
    CollapseThread,
    /// Restore a collapsed thread.
    ExpandThread,
    /// Permanently remove every message in the current folder.
    EmptyFolder,
    // ── Links ─────────────────────────────────────────────────────────
    OpenLinks,
    LinkNext,
    LinkPrev,
    LinkOpen,
    LinkClose,
    /// Preview a text attachment in the attachment list.
    AttachmentView,
    /// Save an attachment into a chosen directory.
    AttachmentSaveAs,
    PreviewScrollDown,
    PreviewScrollUp,
    PreviewClose,
    // ── In-message search ─────────────────────────────────────────────
    SearchMessage,
    MessageSearchInput(char),
    MessageSearchBackspace,
    MessageSearchSubmit,
    MessageSearchCancel,
    NextMatch,
    PrevMatch,
    ClearSelection,
    // ── Sieve filters ─────────────────────────────────────────────────
    OpenSieve,
    OpenKeys,
    OpenSavedSearches,
    SaveSearch,
    SaveSearchInput(char),
    SaveSearchBackspace,
    SaveSearchSubmit,
    SaveSearchCancel,
    SavedSearchNext,
    SavedSearchPrev,
    SavedSearchRun,
    SavedSearchDelete,
    SavedSearchClose,
    KeysNext,
    KeysPrev,
    KeysImport,
    KeysGenerate,
    KeysExport,
    KeysDelete,
    KeysInput(char),
    KeysBackspace,
    KeysSubmit,
    KeysCancel,
    KeysClose,
    SieveNext,
    SievePrev,
    SieveActivate,
    SieveDeactivate,
    SieveEdit,
    SieveNew,
    SieveRename,
    SieveDelete,
    SieveSave,
    SieveClose,
    SieveEscape,
    SieveNameInput(char),
    SieveNameBackspace,
    SieveNameSubmit,
    SieveNameCancel,
    SieveEditorKey(crossterm::event::KeyEvent),
    OpenAttachments,
    AttachmentNext,
    AttachmentPrev,
    AttachmentOpen,
    AttachmentSave,
    AttachmentClose,
    ScrollUp,
    ScrollDown,
    // ── Compose editor ────────────────────────────────────────────────
    ComposeFieldNext,
    ComposeFieldPrev,
    ComposeLeaveBodyNext,
    ComposeLeaveBodyPrev,
    ComposeSend,
    ComposeDiscard,
    ComposeConfirmDiscard,
    ComposeCancelDiscard,
    ComposeInput(char),
    ComposeBackspace,
    /// Activate the focused compose control.
    ComposeEnterInsert,
    /// Leave the focused compose control back to the main compose flow.
    ComposeExitToNav,
    // ── Contacts browser ──────────────────────────────────────────────
    OpenContacts,
    ContactNew,
    ContactDelete,
    ContactEdit,
    ContactSearch,
    ContactSearchInput(char),
    ContactSearchBackspace,
    ContactSearchCancel,
    ContactEditFieldNext,
    ContactEditFieldPrev,
    ContactEditInput(char),
    ContactEditBackspace,
    ContactEditSave,
    ContactEditCancel,
    /// Enter key on contact edit: activates focused action-button or advances field.
    ContactEditActivate,
    OpenIdentities,
    IdentityNew,
    IdentityEditSelected,
    IdentityDelete,
    IdentitySetDefault,
    IdentityListUp,
    IdentityListDown,
    IdentityListClose,
    IdentityEditFieldNext,
    IdentityEditFieldPrev,
    IdentityEditInput(char),
    IdentityEditBackspace,
    IdentityEditToggle,
    IdentityEditSave,
    IdentityEditCancel,
    /// Raw key event forwarded to the compose editor or focused field.
    EditorKey(crossterm::event::KeyEvent),
    None,
}
