/*! Status-bar keybinding hints per view. */

use super::view::View;

pub fn hints(view: View) -> &'static [(&'static str, &'static str)] {
    match view {
        View::EnvelopeList => &[
            ("j/k", "nav"),
            ("Enter", "read"),
            ("v", "triage lane"),
            ("1-5", "route sender"),
            ("L/D", "reply/saved"),
            ("y/Y", "mark reply/save"),
            ("M", "quiet"),
            ("b", "resurface"),
            ("i", "note"),
            ("%", "rename"),
            ("c", "compose"),
            ("d", "del"),
            ("e", "archive"),
            ("m", "move"),
            ("C", "copy"),
            ("!", "flag"),
            ("N", "read"),
            ("S", "sync"),
            ("A", "all read"),
            ("t", "thread"),
            ("space", "select"),
            ("u", "clear sel"),
            ("z", "undo"),
            ("< >", "unread"),
            ("o", "sort"),
            ("r", "thread read"),
            ("/", "search"),
            ("Tab", "folders"),
            ("Ctrl+b", "contacts"),
            ("?", "help"),
        ],
        View::MessageView => &[
            ("j/k", "scroll"),
            ("1-5", "route sender"),
            ("L/D", "reply/saved"),
            ("y/Y", "mark reply/save"),
            ("M", "quiet"),
            ("b", "resurface"),
            ("i", "note"),
            ("%", "rename"),
            ("r", "reply"),
            ("R", "all"),
            ("f", "fwd"),
            ("d", "del"),
            ("e", "archive"),
            ("C", "copy"),
            ("a", "attach"),
            ("Z", "zip all"),
            ("N", "read"),
            ("P", "unlock"),
            ("T", "trust"),
            ("o", "attach"),
            ("/", "find"),
            ("l", "links"),
            ("h", "headers"),
            ("Q", "quotes"),
            ("H", "html"),
            ("c", "to calendar"),
            ("s", "save .eml"),
            ("z", "undo"),
            ("q", "back"),
            ("?", "help"),
        ],
        View::FolderList => &[
            ("j/k", "nav"),
            ("Enter", "select"),
            ("Tab", "emails"),
            ("n", "new"),
            ("r", "rename"),
            ("a-z", "jump"),
            ("d", "delete"),
            ("F", "filters"),
            ("?", "help"),
        ],
        View::FolderPrompt => &[("Enter", "confirm"), ("Esc", "cancel")],
        View::MessageSearch => &[("Enter", "find"), ("Esc", "cancel")],
        View::LinkList => &[("j/k", "nav"), ("Enter", "open"), ("Esc", "close")],
        View::SieveScripts => &[
            ("j/k", "nav"),
            ("Enter", "activate"),
            ("e", "edit"),
            ("n", "new"),
            ("r", "rename"),
            ("d", "delete"),
            ("x", "none active"),
            ("Esc", "close"),
        ],
        View::SieveName => &[("Enter", "create"), ("Esc", "cancel")],
        View::Keys => &[
            ("j/k", "nav"),
            ("i", "import"),
            ("g", "generate"),
            ("x", "export"),
            ("d", "delete"),
            ("Esc", "close"),
        ],
        View::KeysPrompt => &[("Enter", "confirm"), ("Esc", "cancel")],
        View::SaveSearch => &[("Enter", "save"), ("Esc", "cancel")],
        View::SavedSearches => &[
            ("j/k", "nav"),
            ("Enter", "run"),
            ("d", "delete"),
            ("Esc", "close"),
        ],
        View::SieveEdit => &[("Ctrl+s", "save"), ("Esc", "back")],
        View::Settings => &[("space", "toggle"), ("Esc", "close")],
        View::SchedulePrompt => &[("Enter", "schedule"), ("Esc", "cancel")],
        View::ResurfacePrompt => &[("Enter", "resurface"), ("Esc", "cancel")],
        View::PlacePrompt => &[("1-5", "place"), ("Esc", "cancel")],
        View::MessageNote => &[("Enter", "save"), ("Esc", "cancel")],
        View::SubjectAlias => &[("Enter", "rename"), ("Esc", "cancel")],
        View::AttachmentLibrary => &[("j/k", "nav"), ("Enter", "open message"), ("Esc", "close")],
        View::ReadTogether => &[("j/k", "scroll"), ("g/G", "top/end"), ("q/Esc", "back")],
        View::Outbox => &[
            ("j/k", "nav"),
            ("Enter", "send now"),
            ("d", "discard"),
            ("Esc", "close"),
        ],
        View::FilePicker => &[
            ("Enter", "open/attach"),
            ("Backspace", "up"),
            ("Esc", "cancel"),
        ],
        View::AccountEdit => &[
            ("Tab", "field"),
            ("Ctrl+d", "detect"),
            ("Enter", "save"),
            ("Esc", "cancel"),
        ],
        View::AccountList => &[
            ("j/k", "nav"),
            ("Enter", "select"),
            ("s", "default"),
            ("d", "delete"),
            ("Esc", "cancel"),
        ],
        View::Search => &[
            ("Enter", "search"),
            ("Tab", "all folders"),
            ("Esc", "cancel"),
        ],
        View::Help => &[("j/k", "scroll"), ("g/G", "top/end"), ("q/?/Esc", "close")],
        View::MovePrompt => &[("Enter", "move"), ("Esc", "cancel")],
        View::PassphrasePrompt => &[("Enter", "unlock"), ("Esc", "cancel")],
        View::AttachmentView => &[("j/k", "scroll"), ("Esc", "close")],
        View::AttachmentList => &[
            ("j/k", "nav"),
            ("Enter", "open"),
            ("v", "view"),
            ("s", "save"),
            ("S", "save to…"),
            ("Esc", "close"),
        ],
        View::Compose => &[
            ("Tab/j/k", "nav"),
            ("Enter", "insert"),
            ("Esc", "nav/discard"),
        ],
        View::Contacts => &[
            ("t", "tag filter"),
            ("j/k", "nav"),
            ("n", "new"),
            ("e", "edit"),
            ("d", "del"),
            ("/", "search"),
            ("q", "close"),
        ],
        View::ContactSearch => &[("Enter", "confirm"), ("Esc", "cancel")],
        View::ContactEdit => &[
            ("Tab/Enter", "next field"),
            ("Tab→Save→Enter", "save"),
            ("Esc", "cancel"),
        ],
        View::IdentityList => &[
            ("j/k", "nav"),
            ("n", "new"),
            ("e", "edit"),
            ("d", "delete"),
            ("s", "set default"),
            ("q/Esc", "close"),
        ],
        View::IdentityEdit => &[
            ("Tab/Enter", "next field"),
            ("Space", "toggle"),
            ("Tab→Save→Enter", "save"),
            ("Esc", "cancel"),
        ],
    }
}
