pub mod account_store;
pub mod attachments;
pub mod autoconfig;
pub mod errors;
pub mod maildir;
pub mod mime;
pub mod model;
pub mod oauth;
pub mod remote;
pub mod security;
pub mod service;
pub mod session;
pub mod store;
pub mod types;

pub use errors::{MailError, MailErrorKind, MailResult};
pub use model::{Attachment, MessageDocument};
pub use service::{default_mail_service, MailService};
pub use session::IdleOutcome;
pub use types::{Account, Envelope, Folder, Sender};
