/*! Application module wiring. */

mod accessors;
mod account_form;
mod accounts;
mod annotations;
mod archive;
mod attachment_library;
mod attachments;
mod autosave;
mod bulk_reply;
mod bundle_view;
mod clips;
mod compose;
mod compose_actions;
mod compose_attachments;
mod compose_context;
mod contact_harvest;
mod contacts;
mod conversation;
mod crypto;
mod editor;
mod empty_folder;
mod envelope_filter;
mod file_picker;
mod focus;
mod folder_jump;
mod folders;
mod followup;
mod identities;
mod input;
mod links;
mod loading;
mod local_actions;
mod local_search;
mod message_loaded;
mod message_search;
mod model;
mod mouse;
mod move_prompt;
mod navigation;
mod notification_rules;
mod outbox;
mod pgp;
pub(crate) mod pgp_keys;
mod placement;
mod planner;
mod policy;
mod read_together;
mod saved_searches;
mod search_flow;
mod selection;
mod settings;
mod sieve;
mod sieve_actions;
mod smime;
mod snippets;
mod sort_order;
mod stages;
mod threads;
mod triage;
mod undo;
mod unread;
mod worker;

#[cfg(test)]
mod tests;

pub use model::{App, PendingOpenCommand};
